# Generated by Django 4.0.3 on 2022-03-18 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('idbusiness', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('currency', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'business',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('name', models.CharField(max_length=45)),
                ('street', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('town', models.CharField(blank=True, max_length=45, null=True)),
                ('zip', models.IntegerField()),
            ],
            options={
                'db_table': 'location',
                'managed': True,
                'unique_together': {('street', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iditem', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=45)),
                ('item_count', models.IntegerField()),
                ('picture', models.CharField(blank=True, max_length=45, null=True)),
                ('sku', models.CharField(blank=True, max_length=45, null=True, unique=True)),
                ('expire', models.DateField(blank=True, null=True)),
                ('business_name', models.ForeignKey(blank=True, db_column='business_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.business')),
                ('location_name', models.ForeignKey(blank=True, db_column='location_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.location')),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='business',
            name='location_name',
            field=models.ForeignKey(db_column='location_name', on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.location'),
        ),
    ]
