# Generated by Django 4.0.3 on 2022-03-18 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryman', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location_name',
            field=models.ForeignKey(db_column='location_name', default='None', on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.location'),
        ),
    ]
