# Generated by Django 4.0.3 on 2022-03-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryman', '0002_alter_business_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='business_name',
            field=models.ForeignKey(blank=True, db_column='business_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryman.business'),
        ),
    ]
