# Generated by Django 4.0.3 on 2022-03-20 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryman', '0003_alter_item_business_name'),
    ]

    operations = [
                migrations.RemoveField(
            model_name='business',
            name='location_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location_name',
        ),
        migrations.AddField(
            model_name='business',
            name='street_name',
            field=models.ForeignKey(db_column='street_name', default='None', on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.location'),
        ),
        migrations.AddField(
            model_name='item',
            name='street_name',
            field=models.ForeignKey(blank=True, db_column='street_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='business_name',
            field=models.ForeignKey(blank=True, db_column='business_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.business'),
        ),
    ]
