# Generated by Django 4.0.3 on 2022-03-20 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryman', '0004_remove_business_location_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='business_name',
            field=models.ForeignKey(blank=True, db_column='business_name', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventoryman.business'),
        ),
         migrations.AddField(
            model_name='item',
            name='idbusiness',
            field=models.ForeignKey(blank=True, db_column='idbusiness', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.business'),
        ), 
          migrations.RemoveField(
            model_name='item',
            name='business_name',
        ),
         migrations.RemoveField(
            model_name='business',
            name='street_name',
        ),
        migrations.RemoveField(
            model_name='item',
            name='street_name',
        ),
        migrations.AlterUniqueTogether(
            name='business',
            unique_together={('name', 'idbusiness')},
        ),
           migrations.AddField(
            model_name='item',
            name='loc_street_name',
            field=models.ForeignKey(blank=True, db_column='loc_street_name', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.location'),
        ),
          migrations.AddField(
            model_name='business',
            name='loc_street_name',
            field=models.ForeignKey(db_column='loc_street_name', default='None', on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.location'),
        ),
    ]
