# Generated by Django 4.0.3 on 2022-03-25 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryman', '0007_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location_name',
            field=models.ForeignKey(db_column='location_name', default='None', on_delete=django.db.models.deletion.DO_NOTHING, to='inventoryman.location'),
        ),
        migrations.AlterField(
            model_name='item',
            name='location_name',
            field=models.ForeignKey(blank=True, db_column='location_name', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventoryman.location'),
        ),
    
    ]
