# Generated by Django 4.0.3 on 2022-03-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventoryman', '0009_alter_business_location_name_alter_item_idbusiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
